### ISSUE TITLE
Just a helpful note...

### ISSUE THREAD

**Issue by beicnet** [johnstevenson/pl2303-win10#2]
Hi there,

I tried other Windows 10 Fixes, they worked, but not with Visual Basic 6, in other words, I could write to the serial port over Mscomm32.ocx, but did not get back any responses from the Input buffer (only empty lines).

Other terminal applications like Termite and PuTTY where able to communicate with the mentioned fixes listed all over the internet, but not VB6.

Your solution and approach fixed everything and it's just work fine with Visual Basic 6 (Mscomm32.ocx)!

Many thanks for that and great job you did there! 👍 🥇 😉 

Kind regards,
Viktor

**Comment by johnstevenson** [comment]
Hey, thanks for taking the time to report your experience. Glad it worked for you.
