### ISSUE TITLE
Error: Index was out of range.

### ISSUE THREAD

**Issue by skvatboy** [johnstevenson/pl2303-win10#3]
HI
I get a error 
`PS C:\Users\user\Desktop\pl2303-win10-1.0.0-rc2> .\install.bat

Prolific PL-2303 USB-to-Serial driver. Compatible with unsupported
end-of-life microchip versions (PL-2303HXA and PL-2303XA).
Driver version: 3.3.11.152 (12-03-2010)

Checking the DriverStore for installed PL-2303 driver packages
   Found: oem21.inf (31-07-2007, 3.2.0.0)
Checking the System directory for a PL-2303 device driver
   Found: ser2pl64.sys (31-07-2007, 3.2.0.0)
Checking the Registry for a PL-2303 installation program
Error: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index`

The error is if Windows registry object is empty  
`
Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{ECC3713C-08A4-40E3-95F1-7D0704F1CE5E}]
`
![{ECC3713C-08A4-40E3-95F1-7D0704F1CE5E}](https://user-images.githubusercontent.com/5960870/90762726-ccd32800-e2e5-11ea-8758-316010e39f66.JPG)

**Comment by johnstevenson** [comment]
Thanks for the report and research. Fixed in https://github.com/johnstevenson/pl2303-win10/releases/tag/1.0.0
