### ISSUE TITLE
Error: failed to add PL-2303 driver

### ISSUE THREAD

**Issue by humbertosales** [johnstevenson/pl2303-win10#4]
Hello, can you help me?

The script not install driver. There is debug mode?

`
Prolific PL-2303 USB-to-Serial driver. Compatible with unsupported
end-of-life microchip versions (PL-2303HXA and PL-2303XA).
Driver version: 3.3.11.152 (12-03-2010)

Checking the DriverStore for installed PL-2303 driver packages
   Found: none
Checking the System directory for a PL-2303 device driver
   Found: ser2pl64.sys (3.8.37.0)
Checking the Registry for a PL-2303 installation program
   Found: none

This script will install PL-2303 driver, version 3.3.11.152
   Version 3.8.37.0 may be installed and will be replaced.
   Please confirm that you want to do this? [y/n]: y

Adding PL-2303 driver (3.3.11.152) to the DriverStore
   Error: failed to add PL-2303 driver

Restarting your computer and running this script again may resolve the issue.
`

**Comment by humbertosales** [comment]
RESOLVED.

1)  pnputil -e > drivers.txt (ADMINISTRATOR)
2) Lookup OEM number drivers.txt
```
Nome publicado:            oem42.inf
Provedor de pacotes de drivers:   Prolific
Classe:                     Portas (COM e LPT)
Data e versão do driver:   07/20/2020 3.8.37.0
Nome do signatário:               Microsoft Windows Hardware Compatibility Publisher
```

3) pnputil.exe -d oem42.inf /force (ADMIN)
4) Restart 
5) Reexecute install.bat from pl2303-win10 REPO.

**Comment by johnstevenson** [comment]
Glad you fixed this. I'm in the middle of rewriting this as an exe installer. Could you show me the full output of the entry for the driver from pnputil. Thanks.

**Comment by laris** [comment]
> RESOLVED.
> 
> 1. pnputil -e > drivers.txt (ADMINISTRATOR)
> 2. Lookup OEM number drivers.txt
> 
> ```
> Nome publicado:            oem42.inf
> Provedor de pacotes de drivers:   Prolific
> Classe:                     Portas (COM e LPT)
> Data e versão do driver:   07/20/2020 3.8.37.0
> Nome do signatário:               Microsoft Windows Hardware Compatibility Publisher
> ```
> 
> 1. pnputil.exe -d oem42.inf /force (ADMIN)
> 2. Restart
> 3. Reexecute install.bat from pl2303-win10 REPO.

it did work for me.
