### ISSUE TITLE
Error: The term 'pnputil.exe' is not recognized

### ISSUE THREAD

**Issue by Aidenkrz** [johnstevenson/pl2303-win10#6]
Whenever the install script is run I get this error

```
Prolific PL-2303 USB-to-Serial driver. Compatible with unsupported

end-of-life microchip versions (PL-2303HXA and PL-2303XA).
Driver version: 3.3.11.152 (12-03-2010)

Checking the DriverStore for installed PL-2303 driver packages
Error: The term 'pnputil.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Press the enter key to finish:
```

**Comment by Aidenkrz** [comment]
Changing all instances of $pnputil.exe to C:\Windows\System32\pnputil.exe seems to have fixed it for me. Although even though the driver is now installed I still get error code 10.

**Comment by johnstevenson** [comment]
There is something wrong with you `PATH` environment variable, which by default includes your system directory. Perhaps an installer has inadvertently wiped it out.

In cmd.exe you should normally be able to type `where pnputil` which I guess in your case will return an error message. I suppose I could check for this, but if your system directory is not on your path, then not being able to run this script is probably the least of your problems.

**Comment by Aidenkrz** [comment]
yeah honestly no clue why it was like that. still get error code 10 though but i guess im just going to have to live with that forever
